### PR TITLE
ci:Replaced fc22 package files with fc24

### PR DESCRIPTION
**Pull request by david-caro**

### CODE REVIEW

**Comment by david-caro** [comment]
This requires getting [this patch](https://gerrit.ovirt.org/#/c/59893/), so we will have to wait.

**Comment by david-caro** [comment]
ci :shipit:

**Comment by david-caro** [comment]
ci :shipit:

**Comment by david-caro** [comment]
:smile: still some jenkins cleanup to do!

**Comment by david-caro** [comment]
DEBUG util.py:393:  GPG key retrieval failed: [Errno 14] curl#37 - "Couldn't open file /etc/pki/mock/RPM-GPG-KEY-fedora-24-primary"
DEBUG util.py:515:  Child return code was: 1

**Comment by david-caro** [comment]
will try to debug :disappointed:

**Comment by david-caro** [comment]
ci :shipit:

**Comment by gbenhaim** [comment]
ci :shipit:

**Comment by david-caro** [comment]
something wild happened with the build-artifacts_fc24, for some reason it was triggered ~3000 times, making the build that was supposed to be deployed get deleted before the deploy-to-snapshot got to use it....

**Comment by david-caro** [comment]
ci :shipit:

**Comment by gbenhaim** [comment]
How did you figure it out ?

**Comment by david-caro** [comment]
Well, I went to check what was happening with the deploy, and I saw that there were ~20 pending build artifacts jobs for lago fc24... and that the build number was ~3000 vs the ~500 of the other builds have. and it was still being triggered (still don't know why that happened). Just disabled the job to stop the chain, and aborted all the pending jobs. After that it worked ok

**Comment by eedri** [comment]
I am not sure if it's related but I added a soft link from fc24 to fc23
repo for lago on resources.ovirt.org to make job not fail.

If we have fc24 rpms now,  we can remove this link.

**Comment by david-caro** [comment]
I don't think it's related to that issue, but will check too ;)

**Pull request merged**
