### PR TITLE
s/this/these/

### PR DESCRIPTION
**Pull request by mkopta**

### CODE REVIEW

**Comment by david-caro** [comment]
ci test please

**Comment by david-caro** [comment]
Needs rebasing

**Comment by mkopta** [comment]
Rebased.

**Comment by david-caro** [comment]
ci test please

**Comment by eedri** [comment]
ci test please

**Comment by david-caro** [comment]
ci test please

**Comment by david-caro** [comment]
ci test please

**Comment by david-caro** [comment]
ci :shipit:

**Comment by david-caro** [comment]
ci :shipit:

**Comment by david-caro** [comment]
ci :shipit:

**Comment by david-caro** [comment]
r
ci :shipit:

**Comment by david-caro** [comment]
ci :shipit:

**Comment by david-caro** [comment]
ci :shipit:

this is starting to look like a joke :smile:

**Comment by david-caro** [comment]
ci :shipit:

**Comment by david-caro** [comment]
ci :shipit:

**Comment by david-caro** [comment]
ci :shipit: 

... and now issues with the fedora mirrors...

**Comment by david-caro** [comment]
ci :shipit:

**Comment by david-caro** [comment]
Ci is already fixed, sorry for all the noise... several things happened at the same time...

**Comment by david-caro** [comment]
Hmmm, you will have to rebase your branch (I can't as it's on your fork :smile_cat: )

**Comment by mkopta** [comment]
Rebased.

**Comment by david-caro** [comment]
ci :shipit:

**Comment by david-caro** [comment]
ci test please

**Comment by david-caro** [comment]
ci test please

**Comment by david-caro** [comment]
ci :shipit:

**Pull request merged**
