### PR TITLE
Update fedora>23 to use python2-pbr

### PR DESCRIPTION
**Pull request by nvgoldin**
closes: https://github.com/lago-project/lago/issues/173
Signed-off-by: Nadav Goldin <ngoldin@redhat.com>

### CODE REVIEW

**Comment by gbenhaim** [comment]
ci test please

**Comment by nvgoldin** [comment]
ci merge please

**Comment by nvgoldin** [comment]
ci merge please

**Comment by nvgoldin** [comment]
ci merge please

**Comment by nvgoldin** [comment]
ci merge please

**Pull request merged**
