### PR TITLE
Added yaml support for the init config file

### PR DESCRIPTION
**Pull request by david-caro**

### CODE REVIEW

**Comment by ifireball** [comment]
\o/

On 1 March 2016 at 16:48, David Caro <notifications@github.com> wrote:

> ------------------------------
> You can view, comment on, or merge this pull request online at:
>
>   https://github.com/lago-project/lago/pull/151
> Commit Summary
>
>    - Added yaml support for the init conf file
>    - Unit tests for deep_copy and load_virt_stream
>    - Comment in the docs/help about virt config formats
>
> File Changes
>
>    - *M* README.md
>    <https://github.com/lago-project/lago/pull/151/files#diff-0> (2)
>    - *M* lago/cmd.py
>    <https://github.com/lago-project/lago/pull/151/files#diff-1> (13)
>    - *M* lago/prefix.py
>    <https://github.com/lago-project/lago/pull/151/files#diff-2> (31)
>    - *M* lago/utils.py
>    <https://github.com/lago-project/lago/pull/151/files#diff-3> (43)
>    - *M* test-requires.txt
>    <https://github.com/lago-project/lago/pull/151/files#diff-4> (9)
>    - *M* tests/functional/basic.bats
>    <https://github.com/lago-project/lago/pull/151/files#diff-5> (2)
>    - *D* tests/functional/fixtures/basic/suite2.json
>    <https://github.com/lago-project/lago/pull/151/files#diff-6> (48)
>    - *A* tests/functional/fixtures/basic/suite2.yaml
>    <https://github.com/lago-project/lago/pull/151/files#diff-7> (25)
>    - *A* tests/unit/lago/test_utils.py
>    <https://github.com/lago-project/lago/pull/151/files#diff-8> (98)
>
> Patch Links:
>
>    - https://github.com/lago-project/lago/pull/151.patch
>    - https://github.com/lago-project/lago/pull/151.diff
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/lago-project/lago/pull/151>.
>



-- 
*Barak Korren*
bkorren@redhat.com
RHEV-CI Team

**Comment by mykaul** [comment]
Small step to vagrant'ing Lago? 
;-)

**Comment by david-caro** [comment]
We should copy as many good solutions as we can from any other project that faces similar problems if we can :see_no_evil:

**Comment by david-caro** [comment]
ci :shipit:

**Pull request merged**
