### PR TITLE
Added page with some resources for new devs

### PR DESCRIPTION
**Pull request by david-caro**
Just to get started with the technologies and techniques used in lago

### CODE REVIEW

**Comment by david-caro** [comment]
@eedri Not the nicest or more complete, but should be enough to get started and for reference

**Comment by david-caro** [comment]
@gbenhaim Take a look at these docs on getting started, let me know if I should change anything :smiley:

**Comment by david-caro** [comment]
@gbenhaim Take a look at these docs on getting started, let me know if I should change anything :smiley:

**Comment by gbenhaim** [comment]
@david-caro 
The document is well written and very informative for new developers.
When issu that I've found is that the links in "where to go section" are broken

**Comment by david-caro** [comment]
@gbenhaim those are internal links, how did you generate the docs? it should be working well:

   http://jenkins.ovirt.org/job/lago_master_check-patch-fc23-x86_64/369/artifact/exported-artifacts/docs/html/Dev_Bootstrap.html#where-to-go-next

**Comment by gbenhaim** [comment]
@david-caro 
You are right, The links are broken only if you review the document through github.

**Pull request merged**
