### PR TITLE
tests: don't pin yapf version

### PR DESCRIPTION
**Pull request by nvgoldin**
This might require us to update the yapf version locally once in a
while, but we will enjoy new features/bug fixes.

Signed-off-by: Nadav Goldin <ngoldin@redhat.com>

### CODE REVIEW

**Comment by nvgoldin** [comment]
ci test please

**Comment by nvgoldin** [comment]
ci test please

**Comment by nvgoldin** [comment]
ci test please

**Comment by nvgoldin** [comment]
ci test please

**Comment by nvgoldin** [comment]
ci test please

**Comment by nvgoldin** [comment]
ci test please

**Comment by nvgoldin** [comment]
ci merge please

**Comment by nvgoldin** [comment]
ci merge please

**Comment by gbenhaim** [comment]
+1

**Comment by nvgoldin** [comment]
ci merge please

**Comment by nvgoldin** [comment]
ci merge please

**Pull request merged**
