### PR TITLE
Simplified merge repos

### PR DESCRIPTION
**Pull request by mykaul**
KISS method of merging the repos. Just copying all files per version.
Excluding 686 arch, nothing fancy.

### CODE REVIEW

**Comment by mykaul** [comment]
@david-caro  - the failure on EL7 has (hopefully) nothing to do with my patch:
libvirt: QEMU Driver error : monitor socket did not show up: No such file or directory

**Comment by david-caro** [comment]
That's a known issue of libvirt yes

**Comment by david-caro** [comment]
I like the simplification, still have to test it though

**Comment by david-caro** [comment]
Not really, just wanted to give the ovirt system tests a run with it to make sure it does not break anything, but as they are not yet stable I'm focused on fixing them instead. If you verified it, feel free to trigger the merge

**Comment by david-caro** [comment]
heheh :), you should do the merges though the ci process (though it's not working now due to a jenkins bug...) as that also runs the tests as gate (avoiding any errors from getting in) and deploys the newly built version to the stapshot repo.

Now it's ok, but you should really get used to using the ci

**Pull request merged**
