### PR TITLE
Added --list|-l option to snapshots command

### LINKED ISSUE #114: Provide mechanism to list snapshots

### PR DESCRIPTION
**Pull request by david-caro**
fixes #114

### CODE REVIEW

**Comment by david-caro** [comment]
It's based on the pr #140

**Comment by david-caro** [comment]
ci merge please

**Comment by ifireball** [comment]
id rather itd been 'list' and not '--list'
בתאריך 26 בפבר׳ 2016 15:03,‏ "Lago CI bot" <notifications@github.com> כתב:

**Comment by david-caro** [comment]
The way that snapshot is currently implemented did not allow that (it expect the name of the snapshot, and list is as valid as any)

**Pull request merged**
