### PR TITLE
Add 'start-hosts' and 'stop-hosts' to ovirt sub-command

### PR DESCRIPTION
**Pull request by mykaul**
This command will set all hosts to Maintenance ('stop-hosts')
Or to Up ('start-hosts')

### CODE REVIEW

**Comment by gbenhaim** [comment]
ci merge please

**Comment by mykaul** [comment]
-1 from me. Found a typo.

**Comment by gbenhaim** [comment]
@mykaul 
Did you fix the typo? can i merge ?

**Comment by gbenhaim** [comment]
ci merge please

**Comment by gbenhaim** [comment]
ci merge please

**Comment by gbenhaim** [comment]
ci merge please

**Comment by gbenhaim** [comment]
ci merge please

**Pull request merged**
