### PR TITLE
ovirtlago: Start all VMs in 'lago ovirt start'

### PR DESCRIPTION
**Pull request by nvgoldin**
After checking all SDs are in 'active' mode.

fixes: https://github.com/lago-project/lago/issues/486

Signed-off-by: Nadav Goldin <ngoldin@redhat.com>

### CODE REVIEW

**Comment by gbenhaim** [comment]
@nvgoldin I would suggest to add an option to `lago ovirt start` which allows to skip this phase, e.g don't power on l2 vms and thus there is no need to wait for the storage (it will help to debug storage issues).

**Comment by nvgoldin** [comment]
@gbenhaim - good point. done.
The syntax is:
```
lago ovirt start --no-vms
```

Also added some tests/changes needed for the tests.

**Comment by mykaul** [comment]
I must say that IMHO, the default should NOT be start L2 VMs, and this should be done only by '--with-vms'  parameter.

**Comment by nvgoldin** [comment]
@mykaul - sure, I'll change it(have no strong opinion here - both makes sense in some way).

**Comment by nvgoldin** [comment]
ci test please

**Comment by nvgoldin** [comment]
```
10:53:44 Exception occurred:
10:53:44   File "/home/jenkins/workspace/lago_master_github_check-patch-el7-x86_64/lago/tests/docs_venv/lib/python2.7/site-packages/sphinx/domains/python.py", line 317, in before_content
10:53:44     if prefix:
10:53:44 UnboundLocalError: local variable 'prefix' referenced before assignment
10:53:44 The full traceback has been saved in /tmp/sphinx-err-6N3tJy.log, if you want to rep
```
Hitting a new sphinx bug/regression I think(its not our ``prefix`` there..).

**Comment by nvgoldin** [comment]
ci merge please

**Pull request merged**
