### PR TITLE
Collect hosted-engine logs

### PR DESCRIPTION
**Pull request by didib**
Change-Id: Ic3c53c9046078f6c9eeb10b09b24cbdcf608a382
Signed-off-by: Yedidyah Bar David didi@redhat.com

### CODE REVIEW

**Comment by didib** [comment]
Looked at [1] and could not find hosted-engine logs.
I am new to lago. grepped a bit and found this place where it seems I can try adding them. I'd expect it to be in the repo 'ovirt-system-tests', not 'lago'. Also not sure what happens with tests that are not hosted-engine, where these logs will not exist. Will this fail the job? If so, how do I cleanly fix this? Perhaps add a new vm-type? I am just guessing from the code, didn't yet readthedocs.

[1] http://jenkins.ovirt.org/view/oVirt%20system%20tests/job/ovirt_4.0_he-system-tests/lastSuccessfulBuild/artifact/

**Comment by didib** [comment]
Perhaps something like #342

**Comment by david-caro** [comment]
Yep, I think that the other one is the way to go, this is adding the list of artifacts to any host, hosted engine or not.

**Comment by didib** [comment]
Abandoning in favor of #342 (which is merged) and https://gerrit.ovirt.org/65286 .

**Pull request closed without merging**
