### PR TITLE
Speed up test by skipping the bootstrap during init

### PR DESCRIPTION
**Pull request by david-caro**
This also adds the new '--skip-bootstrap' option to the init command
to allow skipping it.

### CODE REVIEW

**Comment by david-caro** [comment]
This has chopped off ~5 min from the test run time (that's ~20% runtime reduction)

**Comment by mykaul** [comment]
On my poor system, only 2:30 - but still - excellent! Do we have enough ready-made images, that we really won't need the bootstrapping?

**Comment by david-caro** [comment]
not right now, my idea is to serve along with the images the ssh key too (we are giving only the root pass) and thus allow skipping the bootstrap by default

**Comment by david-caro** [comment]
ci :shipit:

**Comment by david-caro** [comment]
ci :shipit:

**Comment by david-caro** [comment]
ci :shipit:

**Comment by david-caro** [comment]
ci :shipit:

We are hitting https://bugzilla.redhat.com/show_bug.cgi?id=854983 on some slaves

**Comment by david-caro** [comment]
ci :shipit:

**Comment by david-caro** [comment]
ci :shipit:

**Comment by david-caro** [comment]
ci :shipit:

**Comment by david-caro** [comment]
ci test please

**Comment by david-caro** [comment]
ci test please

**Comment by david-caro** [comment]
ci :shipit:

**Comment by david-caro** [comment]
ci :shipit:

**Comment by david-caro** [comment]
ci :shipit:

**Pull request merged**
