### PR TITLE
Fix el7 dirlock

### PR DESCRIPTION
**Pull request by david-caro**

### CODE REVIEW

**Comment by david-caro** [comment]
ci :shipit:

**Comment by david-caro** [comment]
ci :shipit:

**Comment by mykaul** [comment]
@david-caro  - are you sure we need this lock?

**Comment by david-caro** [comment]
Yep, as we don't just run reposync once, but retry and if failed do a check on the downloaded repos consistence we need to lock other lago processes from doing the same (another question is if we should be doing all that process, that I'm not sure about, but I'd leave that for one of the meetings or ml discussion)

**Comment by david-caro** [comment]
ci :shipit:

**Pull request merged**
