### PR TITLE
reposetup: be more verbose on reposync failure

### PR DESCRIPTION
**Pull request by sandrobonazzola**
Added error logging on reposync retry error.
If something prevent the reposync to complete while
running in jenkins it becomes hard to understand what failed
without having the output of the reposync command.
This patch add stdout and stderr from reposync command
to be printed before aborting the sync.

Signed-off-by: Sandro Bonazzola <sbonazzo@redhat.com>

### CODE REVIEW

**Comment by david-caro** [comment]
ci test please

**Comment by sandrobonazzola** [comment]
ci test please

**Comment by sandrobonazzola** [comment]
@david-caro looks like ci has some issue. can't see the result of the tests

**Comment by gbenhaim** [comment]
ci test please

**Comment by gbenhaim** [comment]
ci merge please

**Comment by sandrobonazzola** [comment]
@gbenhaim merge failed

**Comment by gbenhaim** [comment]
ci merge please

**Pull request merged**
