### PR TITLE
Fixes #20

### LINKED ISSUE #20: When there are lock errors when registering nets, there's no clear error
Instead it usually fails with KeyError for 'gw' key as Prefix._allocate_subnets() fails silently

### PR DESCRIPTION
**Pull request by gbenhaim**
ci:+1:

### CODE REVIEW

**Comment by gbenhaim** [comment]
ci:+1:

**Comment by gbenhaim** [comment]
ci test please

**Comment by gbenhaim** [comment]
ci test please

**Comment by gbenhaim** [comment]
ci merge please

**Comment by david-caro** [comment]
ci merge please

**Comment by david-caro** [comment]
ci :shipit:

**Comment by david-caro** [comment]
ci :shipit:

**Comment by david-caro** [comment]
ci merge please

**Pull request merged**
