### PR TITLE
Fix lago list

### PR DESCRIPTION
**Pull request by gbenhaim**
1. Fixed lago list to print the available prefixes in a workidir.

2. Fixed the docstrings.

3. Added cli functional test.

Signed-off-by: gbenhaim <galbh2@gmail.com>

### CODE REVIEW

**Comment by gbenhaim** [comment]
1. After looking at the code of `lago list` I've realized that its purpose is to list all the prefixes in a workdir,   so fixing the code and the help message.

2. Personally, I don't see any benifit to group prefixes in a workdir (as long as they don't share the  
   same files).

3. Yet, I think that working with multiple prefixes is usefull, and that we should provide a new command,   
     `lago workon` to switch between them (similar to virtualenvwrapper workon).

4. In addition to 3, It will be nice to issue commands to the current env (that was specified with `lago  
   workon`) regardless of the current directory.

5. It will be nice if a user could list all of his existing envs + some description on those envs (as 
    specified in the init file or to `lago init`)

**Comment by gbenhaim** [comment]
closes https://github.com/lago-project/lago/issues/620

**Comment by nvgoldin** [comment]
> Yet, I think that working with multiple prefixes is usefull, and that we should provide a new command,
lago workon to switch between them (similar to virtualenvwrapper workon).

That is what ``lago set-current`` is supposed to do I think. Or you mean *globally*?

**Comment by gbenhaim** [comment]
globally !

**Comment by gbenhaim** [comment]
ci test please

**Comment by nvgoldin** [comment]
``venvwrapper`` is a little different because it assumes you put all your venvs in the same directory, and then you run ``export WORK_ON=...``.

**Comment by gbenhaim** [comment]
Correct, but you are talking about implementation, and I've just mentioned the required (IMO) functionality.

**Comment by gbenhaim** [comment]
ci test please

**Comment by gbenhaim** [comment]
ci test please

**Comment by gbenhaim** [comment]
ci merge please

**Pull request merged**
