### PR TITLE
Add sanlock log to log collection

### PR DESCRIPTION
**Pull request by mykaul**
This PR adds /var/log/sanlock.log to be collected from the hosts.

### CODE REVIEW

**Comment by david-caro** [comment]
@mykaul can you rebase please? CI should be working ok now, so we can retake merging and testing pull requests (this one included :wink: )

**Comment by mykaul** [comment]
@david-caro as always, failed rebasing. There are various issues (that are not related to my fix), but I forgot yapf :(

**Comment by mykaul** [comment]
@david-caro Apparently, it's not all my fault: when I ran the yapf command ('yapf --style .style.yapf --in-place --recursive . ') it changed many files, not only my change... 

Changes not staged for commit:
  (use "git add <file>..." to update what will be committed)
  (use "git checkout -- <file>..." to discard changes in working directory)

	modified:   docs/conf.py
	modified:   lago/cmd.py
	modified:   lago/config.py
	modified:   lago/log_utils.py
	modified:   lago/plugins/__init__.py
	modified:   lago/plugins/cli.py
	modified:   lago/plugins/output.py
	modified:   lago/plugins/vm.py
	modified:   lago/prefix.py
	modified:   lago/service.py
	modified:   lago/ssh.py
	modified:   lago/sysprep.py
	modified:   lago/templates.py
	modified:   lago/utils.py
	modified:   lago/virt.py
	modified:   lago/vm.py
	modified:   lago/workdir.py
	modified:   ovirtlago/__init__.py
	modified:   ovirtlago/cmd.py
	modified:   ovirtlago/reposetup.py
	modified:   ovirtlago/virt.py
	modified:   scripts/version_manager.py
	modified:   setup.py
	modified:   tests/unit/lago/test_libvirt_utils.py
	modified:   tests/unit/lago/test_workdir.py
	modified:   tests/unit/test_config.py
	modified:   tests/unit/test_dirlock.py


Strange, no?

**Comment by mykaul** [comment]
My change was supposed to be only in ovirtlago/virt.py :
 

 
-        return set(inherited_artifacts + ['/var/log/vdsm', ])
+        return set(
+            inherited_artifacts + ['/var/log/vdsm',
+                                   '/var/log/sanlock.log', ]
+        )

**Comment by david-caro** [comment]
Make sure to be using the correct yapf version, the newer ones have changed quite a lot the behavior... (enough to stop being pep8 compliant)

**Comment by mykaul** [comment]
Upgraded from 0.9 to 0.11.0 - same result.

**Comment by david-caro** [comment]
You should be using 0.7.1 (see the test-requires.txt)

**Comment by mykaul** [comment]
OK, with 0.7.1 (which is MUCH slower than current versions), I got only:
```
	modified:   ovirtlago/virt.py
	modified:   tests/unit/test_dirlock.py
```

Of course, I only changed ovirtlago/virt.py ...
But I don't mind sending both, I guess.

**Comment by david-caro** [comment]
That last one should not have been changed :/, though I don't really think that it's an issue, you can send both (the actual tests only check the changed files, so if you don't send the test one, it will not check it)

**Comment by david-caro** [comment]
did you really want to close it?

**Comment by mykaul** [comment]
Opened PR 290 instead.

**Pull request closed without merging**
