### PR TITLE
Switch to optional freeze the FS before logs extraction.

### PR DESCRIPTION
**Pull request by mykaul**
More importantly, by default, the call will not freeze the FS.
There is no reason to do it, for two reasons:
1. We open the FS in read-only - so no corruption can happen.
2. The system is quite stable - we already passed whatever
test we passed or failed - all logs are in the system already
(especially as in ovirt-system-tests we complete the suite after
failure)

This may prevent issues when the hosts are disconnected due to a
long freeze

### CODE REVIEW

**Comment by eedri** [comment]
Failing on:
19:23:32 ##!
19:23:32 ./lago/prefix.py:745:27: F999 dictionary key 'name' repeated with different values
19:23:32 ./lago/prefix.py:746:27: F999 dictionary key 'name' repeated with different values
19:23:32 ./lago/templates.py:264:1: E305 expected 2 blank lines after class or function definition, found 1
19:23:32 make: *** [check-local] Error 1
19:23:32 ~~~~~~~~~~~~~~~~~~~~

**Comment by mykaul** [comment]
ci test please

**Comment by mykaul** [comment]
@nvgoldin @gbenhaim @david-caro : sent an email to lago-devel - yapf and flake8 disagree with each other, and I'm stuck on this (which has NOTHING to do with this patch!)

**Comment by gbenhaim** [comment]
+1

**Comment by gbenhaim** [comment]
ci merge please

**Pull request merged**
