### PR TITLE
[ost-plugin] cleanup unused commands

### PR DESCRIPTION
**Pull request by nvgoldin**
1. Removed stop/start/snapshot functions and their relevant
private functions in ovirtlago/__init__.py, in OST
we use the direct 'lago stop/start' commands.
2. Updated setup.cfg entry points
3. Not sure why but running yapf requested changes
to ../tests/unit/test_dirlock.py, has nothing to do
with the patch subject.

preparation for https://github.com/lago-project/lago/issues/350

### CODE REVIEW

**Comment by nvgoldin** [comment]
testing this on 4.0 suite, couldn't find any evidence of their usage(``ovirt snapshot/start/stop``), if anyone knows if we're using them somewhere, this is time to say :)

**Comment by eedri** [comment]
:+1: for the cleanup

**Comment by david-caro** [comment]
Yep, I think that in the very beginning those commands were specific for ovirt, but we moved them to the generic lago early, and just kept them to retain backwards compatibility, if nobody complains should be ok to remove.

**Comment by nvgoldin** [comment]
ci merge please

**Comment by nvgoldin** [comment]
thanks for the inputs, merging.

**Pull request merged**
