### PR TITLE
added test_equals* tests to testlib

### PR DESCRIPTION
**Pull request by leongold**
Added testlib tests testing for method to value equality.

The primary motivation behind this is to be able to receive informative assertion errors for failed tests, and to be able to skip the step of passing anonymous (or otherwise) functions as test input.

### CODE REVIEW

**Comment by mykaul** [comment]
@leongold - there's no description to the patch?

**Comment by leongold** [comment]
@mykaul sorry, are you referring to the commit message? (it is present, but perhaps you're referring to something else)

**Comment by david-caro** [comment]
ci test please

**Comment by david-caro** [comment]
ci test please

**Comment by leongold** [comment]
would "ci test please" work for me, too?

**Comment by david-caro** [comment]
Nop, sorry, only admins/team members. :)

**Comment by nvgoldin** [comment]
ci test please

**Comment by gbenhaim** [comment]
ci test please

**Comment by leongold** [comment]
el7 build timed out:

19:16:19 Build timed out (after 360 minutes). Marking the build as failed.
19:16:19 Build was aborted

**Comment by nvgoldin** [comment]
ci test please

**Comment by leongold** [comment]
I'm not sure what's causing the el7 build to timeout, seems to be unrelated?

**Comment by nvgoldin** [comment]
> I'm not sure what's causing the el7 build to timeout, seems to be unrelated?

Should be fixed after https://github.com/lago-project/lago/pull/391 is merged, remind me to re-trigger the tests.

Except that - looks good to me. Please verify it with OST(master/4.0) is probably enough. 
https://gist.github.com/nvgoldin/c7c20acc73de85c9a0a2690ffe260da2 - hackish script I use to build lago and run ost with it(you need mock for that - http://ovirt-infra-docs.readthedocs.io/en/latest/CI/Build_and_test_standards.html)

**Comment by leongold** [comment]
I had a bit of trouble following your script ("lago-build-scripts"?), but with Gal's help I've set a virtualenv and successfully ran OST using my forked lago.

https://gist.github.com/leongold/2d0a25a4ae8f65216feae44a4a3e96cb

**Comment by nvgoldin** [comment]
ci test please

**Comment by leongold** [comment]
ci test please

**Comment by nvgoldin** [comment]
ci merge please

**Comment by nvgoldin** [comment]
ci merge please

**Comment by nvgoldin** [comment]
ci merge please

**Pull request merged**
