### PR TITLE
Added /var/log/sanlock.log to the log collection from hosts

### PR DESCRIPTION
**Pull request by mykaul**
Take 2 of trying to add /var/log/sanlock.log to the log collection our the VDSM hosts.

### CODE REVIEW

**Comment by david-caro** [comment]
hmmm... it says you have to rebase :/

**Comment by mykaul** [comment]
Tried with the 'Update' button... Let's see how that works.

**Comment by david-caro** [comment]
That adds a dummy 'merge' commit to the branch, that when merged again to master, is followed by yet another merge commit...

**Comment by mykaul** [comment]
@david-caro - so should I merge or not this one?

**Comment by david-caro** [comment]
Yes, but use the ci process of sending the message to jenkins, so it does the build+test+release pipeline fully:
    http://lago.readthedocs.io/en/stable/CI.html#getting-the-pull-request-merged

**Comment by mykaul** [comment]
ci merge please

**Comment by mykaul** [comment]
ci merge please

**Pull request merged**
