### PR TITLE
Added the destroy command

### LINKED ISSUE #110: 'destroy' command
I'd like to request a destroy command that properly stops, does any cleanup and removes an environment. I've already ran into accidentally doing `rm -rf environment/` without running `lago stop`. Help me protect myself from myself.

### PR DESCRIPTION
**Pull request by david-caro**
It will cleanup (stop vms, unregister everything...) and remove the
whole prefix, it will ask for confirmation unless --yes|-y is passed

Fixes #110

### CODE REVIEW

**Comment by david-caro** [comment]
ci merge please

**Comment by ifireball** [comment]
So what will 'clean' do in contrast?
This seems to be going down the otopi slope with its 15 stages of
installation...

On 29 February 2016 at 22:08, David Caro <notifications@github.com> wrote:

> ci merge please
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/lago-project/lago/pull/144#issuecomment-190361329>.
>



-- 
*Barak Korren*
bkorren@redhat.com
RHEV-CI Team

**Comment by david-caro** [comment]
Cleanup only removes any leases (network and such) and removes the 'initialized' file that tags a prefix as such

David Caro

El 29/2/2016 21:23, Barak Korren <notifications@github.com> escribió:

So what will 'clean' do in contrast?
This seems to be going down the otopi slope with its 15 stages of
installation...

On 29 February 2016 at 22:08, David Caro <notifications@github.com> wrote:

> ci merge please
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/lago-project/lago/pull/144#issuecomment-190361329>.
>



-- 
*Barak Korren*
bkorren@redhat.com
RHEV-CI Team

**Comment by david-caro** [comment]
I agree it's a bit confusing, I think that we can remove the need for the initialized file, and the cleanup at some point. For now, you can think of the destroy as 'cleanup + rm -rf', that it's actually what it does

David Caro

El 29/2/2016 21:23, Barak Korren <notifications@github.com> escribió:

So what will 'clean' do in contrast?
This seems to be going down the otopi slope with its 15 stages of
installation...

On 29 February 2016 at 22:08, David Caro <notifications@github.com> wrote:

> ci merge please
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/lago-project/lago/pull/144#issuecomment-190361329>.
>



-- 
*Barak Korren*
bkorren@redhat.com
RHEV-CI Team

**Comment by ifireball** [comment]
is there anything the user can do after running 'cleanup' besides 'destroy'?

On 29 February 2016 at 23:56, David Caro <notifications@github.com> wrote:

> I agree it's a bit confusing, I think that we can remove the need for the
> initialized file, and the cleanup at some point. For now, you can think of
> the destroy as 'cleanup + rm -rf', that it's actually what it does
>
> David Caro
>
> El 29/2/2016 21:23, Barak Korren <notifications@github.com> escribió:
>
> So what will 'clean' do in contrast?
> This seems to be going down the otopi slope with its 15 stages of
> installation...
>
> On 29 February 2016 at 22:08, David Caro <notifications@github.com> wrote:
>
> > ci merge please
> >
> > —
> > Reply to this email directly or view it on GitHub
> > <https://github.com/lago-project/lago/pull/144#issuecomment-190361329>.
> >
>
>
>
> --
> *Barak Korren*
> bkorren@redhat.com
> RHEV-CI Team
>
> —
> Reply to this email directly or view it on GitHub.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/lago-project/lago/pull/144#issuecomment-190415341>.
>



-- 
*Barak Korren*
bkorren@redhat.com
RHEV-CI Team

**Pull request merged**
