### PR TITLE
Add vm-type ovirt-he-host

### PR DESCRIPTION
**Pull request by didib**
Change-Id: I9f0305681cabdcd87a079806a60fecdd1e5ac5be
Signed-off-by: Yedidyah Bar David didi@redhat.com

### CODE REVIEW

**Comment by didib** [comment]
This is an alternative to #341, to be used by https://gerrit.ovirt.org/65286 . Not sure if any of them is a good idea.

**Comment by david-caro** [comment]
ci test please

this looks ok for me too

**Comment by pilou-** [comment]
@didib one style check failed, another empty line must be added before `class HEHostVM(HostVM):` in [ovirtlago/virt.py](https://github.com/didib/lago/blob/b97019dc2f67d0681bf8cc84b158818f6ed87bc9/ovirtlago/virt.py#L210). Here is a [PR](https://github.com/didib/lago/pull/1) on your PR :)

**Comment by didib** [comment]
Thanks, @pilou- !

**Comment by nvgoldin** [comment]
ci test please

**Comment by nvgoldin** [comment]
Hi @didib , can you update with master and squash the commits?

**Comment by nvgoldin** [comment]
ci test please

**Comment by nvgoldin** [comment]
ci test please

**Comment by nvgoldin** [comment]
ci test please

**Comment by didib** [comment]
ci test please

**Comment by nvgoldin** [comment]
@eedri  - this skipped the CI tests, though no worries it will happend on next merge.
when commenting 'ci merge please' it triggers the CI(with more extensive tests than check patch), if passes, lago-bot merges the patch and deploys it to lago's unstable repo.

**Comment by eedri** [comment]
Thanks for the clarification.

**Pull request merged**
