### PR TITLE
New progress bar test.

### PR DESCRIPTION
**Pull request by mykaul**
It blinks a bit over the terminal, I hope it's OK
in Jenkins

### CODE REVIEW

**Comment by david-caro** [comment]
This does not show any output on jenkins

**Comment by mykaul** [comment]
I don't know if it's good or bad that there's nothing on Jenkins - I assume it did download the templates of course. On a terminal (from a hotel Wifi over VPN) it blinks a bit too much to my taste, but certainly better than my primitive progress.

**Comment by david-caro** [comment]
Maybe use a simple Bar, that uses # as the filling, not so 'blinky'.

I'd like though for it to show on jenkins too, as there you have the same issue, you don't know if it's stuck or not if no progress is shown

**Comment by david-caro** [comment]
I've just realized that is the same bar (at least the style) that pip uses itself :smile:

**Comment by mykaul** [comment]
I must be doing something wrong if I end up with all this. I've done a 'pull --rebase' to get all of this. Perhaps shouldn't have and merged or squashed?

**Comment by david-caro** [comment]
mm, yep, this looks wrong, are you pulling from your fork's master? or from lago-project/lago master? probably you'd want to update your fork's master too (forcing from lago-project if needed, like git push myrepo remotes/lago-project/heads/master:refs/heads/master --force or similar)

**Comment by david-caro** [comment]
It's a bit disappointing that I can't help you with any pull request either :/

**Comment by mykaul** [comment]
Not sure:
 1188  git commit
 1189  git fetch upstream
 1190  git rebase upstream/master
 1191  make clean
 1192  make rpm
 1193  scp rpmbuild/RPMS/noarch/*.rpm mini@ykaul-mini.tlv.redhat.com:/tmp
 <--- testing
 1194  make check
 1195  make clean
 1196  git status
 1197  git diff
 1198  git push
 1199  git fetch upstream
 1200  git rebase -v upstream/master
 1201  git push     <-- this fails

ykaul@ykaul lago]$ git push
To git@github.com:mykaul/lago.git
 ! [rejected]        new_progress -> new_progress (non-fast-forward)
error: failed to push some refs to 'git@github.com:mykaul/lago.git'
hint: Updates were rejected because the tip of your current branch is behind
hint: its remote counterpart. Integrate the remote changes (e.g.
hint: 'git pull ...') before pushing again.
hint: See the 'Note about fast-forwards' in 'git push --help' for details.


 1202  git pull --rebase
 1203  git push

**Comment by david-caro** [comment]
let's try this:
```shell
git clone git@github.com:mykaul/lago
cd lago
git remote add lago-project git@github.com:lago-project/lago
git fetch lago-project
git reset --hard lago-project/master
git push --force origin master # at this point, your fork's master and lago master should have the same history
git checkout new_progress
git reset --hard origin/master
git cherry-pick d69835937c842dd3bf2a7f368da45130e9030170 # this is the commit that adds the progress bar
mock_runner.sh -m fc23 # to run the tests, including build and installation for fc23
git push --force origin new_progress
```

**Pull request closed without merging**
