### PR TITLE
tests: update cirros image to start cirros-dhcpc explicitly

### PR DESCRIPTION
**Pull request by nvgoldin**
This should resolve the problem that the image didn't get an IP during the
tests, if it boot up too 'quickly', which might be caused by
a bug in dnsmasq/libvirt(the configurations were not deployed yet).

issue: https://github.com/lago-project/lago/issues/399

Signed-off-by: Nadav Goldin <ngoldin@redhat.com>

### CODE REVIEW

**Comment by ifireball** [comment]
I'd rather we have a logo-level solution for this, so using fast images with lago does not become a "crime"

**Comment by nvgoldin** [comment]
1. An attempt to resolve it "inside lago" was done in https://github.com/lago-project/lago/pull/405, turns out it wasn't enough.
2. We don't know yet the true core of the problem, and resolving this will require some more time(as you see I didn't add  'closes:', so the ticket is going to be left open)
3. Meanwhile, this blocks CI and causes annoying failures that add a lot of headache. And most importantly, the only place we see this happening is on the functional tests using the cirros image.

So yes, I agree, but I rather get this going now. The ticket will be left open.

**Comment by mykaul** [comment]
Do we need an updated image in ovirt.org Glance server as well?

**Comment by ifireball** [comment]
maybe we can `dhcping` dnsmasq? or perhaps just try a dns query against it? I also have a piece of pure Python code that can do DHCP querying, if you don't want to depend on another a command-line tool...

**Comment by ifireball** [comment]
> Do we need an updated image in ovirt.org Glance server as well?

I wouldn`t want to host tweaked images there, I need to able to grantee users that images there were not tampered with.

**Comment by nvgoldin** [comment]
> maybe we can dhcping dnsmasq? or perhaps just try a dns query against it? I also have a piece of pure Python code that can do DHCP querying, if you don't want to depend on another a command-line tool...

great 👍 , would be nice if you can put it somewhere and I could try to query dnsmasq before the run stage. Though as I said, I don't think it contradicts this PR. The cirros image serves us for testing, as long it does allow us to test what we want(and how quickly libvirt deploys dnsmasq configuration is not one of our tests), I don't mind tweaking it.

**Comment by nvgoldin** [comment]
I ran the 'check-merged' twice on one of the hyper visors(where it happened before as supposedly it deployed the image too quickly) and all went good. 
http://jenkins.ovirt.org/job/lago_master_check-merged-el7-x86_64/303/
http://jenkins.ovirt.org/job/lago_master_check-merged-el7-x86_64/302/

**Comment by nvgoldin** [comment]
I'm abandoning this in favour of https://github.com/lago-project/lago/pull/421,
1. I think https://github.com/lago-project/lago/pull/421 is better as it will allow(if needed) to increase the wait time, and the workaround is inside lago. 
2. Major issue with this PR which was brought to my attention by @ifireball: it will increase (most likely forever) our git repository by around 12MB.

**Comment by mykaul** [comment]
I still have no doubt that we need to try with newer cirros images (true, they have not released one in ages, but they are available). Examples of potentially relevant commits:
https://git.launchpad.net/cirros/commit/?id=4285160b0d0b7f9be19f7464b61df3ad1decd3cb - IPv6 information
https://git.launchpad.net/cirros/commit/?id=6752f081363a0d38b1dd41593b47ac60b0caab52 - virtio-SCSI (which we need!)
 https://git.launchpad.net/cirros/commit/?id=c475073deef2e45ffc61d469a0b6254a365a6d2c - another fix in DHCP ...
https://git.launchpad.net/cirros/commit/?id=2d3e303f5f940c411feaa74917988f8c397a2ef4 - much newer kernel

**Comment by nvgoldin** [comment]
@mykaul  - I agree, I'll open an issue there(when launchpad lets me register!) to check when they are going to do another release. When they do - we can test it thoroughly and pay the price of 12MB in the git repo(rather pay it once..)

**Comment by mykaul** [comment]
@nvgoldin try http://download.cirros-cloud.net/daily/20161201/

**Pull request closed without merging**
