### PR TITLE
Add AUTHORS to 'make clean' command

### PR DESCRIPTION
**Pull request by mykaul**
Also, add AUTHORS to .gitignore

### CODE REVIEW

**Comment by david-caro** [comment]
I think this hit the jenkins issues we had
ci test please

**Comment by mykaul** [comment]
@david-caro  - why was it assigned to me? What do I need to do here?

**Comment by david-caro** [comment]
@mykaul Because you opened it, and you are the only one that has rights to update the branch so noone else is able to do any updates, it looks ok to me so I will try to merge it once it passes the tests, so not really anything needed on your side (you can also merge it yourself if you want :grinning:)

**Comment by david-caro** [comment]
still have to figure out a good review process...

**Comment by mykaul** [comment]
I don't merge. I do enough damage from my own branch ;-)

**Comment by david-caro** [comment]
ci :shipit:

**Pull request merged**
