### PR TITLE
Make paramiko v1.16 work with python2-crypto again

### PR DESCRIPTION
**Pull request by nvgoldin**
1. Monkeypatch the paramiko.transport.Transport._get_cipher method
to work with python2-crypto.x86_64 0:2.6.1-13.el7. Based on:
https://github.com/paramiko/paramiko/pull/714

2. Explicitly require paramiko >= v2.1.1 for fc >= 24, which does not
depends on python2-crypto.

(1) should be reverted once the BZ is resolved and a new paramiko v1.x version is pushed to epel.

Unfortunately, I'm including here 2 unrelated commits to fix the functional tests, as otherwise this PR will fail(and they will fail without this fix).
1. Clean yum/dnf metadata before building the RPM.
2. Depress the lago 'group' warnings during the test by enforcing running bats under 'lago' gid. 

closes: https://github.com/lago-project/lago/issues/440
closes: https://github.com/lago-project/lago/issues/409
https://bugzilla.redhat.com/show_bug.cgi?id=1419312

Signed-off-by: Nadav Goldin <ngoldin@redhat.com>

### CODE REVIEW

**Comment by nvgoldin** [comment]
ci test please

**Comment by nvgoldin** [comment]
ci merge please

**Comment by nvgoldin** [comment]
ci test please

**Comment by eedri** [comment]
ci test please

**Comment by nvgoldin** [comment]
@eedri - I'm still working on it, as the tests are failing(for different reasons), I'll merge as soon as possible.

**Comment by nvgoldin** [comment]
last failure is unrelated, it checkouted a different commit.

**Comment by nvgoldin** [comment]
ci test please

**Comment by nvgoldin** [comment]
ci test please

**Comment by nvgoldin** [comment]
ci test please

**Comment by nvgoldin** [comment]
ci merge please

**Pull request merged**
