### PR TITLE
README fixes

### PR DESCRIPTION
**Pull request by mkopta**

### CODE REVIEW

**Comment by david-caro** [comment]
Thanks Martin!

ci test please

**Comment by david-caro** [comment]
ci test please

Hmm... the trigger is only if it goes first xd

**Comment by mkopta** [comment]
Uhm, sorry, accidentally appended another commit into this pull request. Should I get rid of it?

**Comment by david-caro** [comment]
If they are small and/or related they can go together, just flag the pr with 'needs_review' once you have finished

**Comment by mkopta** [comment]
Alrigth, thanks! :-)

**Comment by mkopta** [comment]
Hmm, I guess I don't really have permissions to add labels. Could you please add the `needs_review`?

Sorry for making it so messy, this is my first pull request into Lago :-)

**Comment by david-caro** [comment]
No problem, I actually thought that the pr owner was able to change the flags :/, will have to recheck the flow!

**Comment by david-caro** [comment]
ci :shipit:

**Pull request merged**
