### PR TITLE
tests: run systemd-analyze blame after each run

### PR DESCRIPTION
**Pull request by nvgoldin**
Will be available in:

exported-artifacts/test_results/functional-sdk/test_results_sdk/test_sdk_sanity/systemd-analyze-<VM_NAME>.txt

or under test_results if running locally:
```bash
$ pytest -vvv -s /tests/functional-sdk
```

fixes: https://github.com/lago-project/lago/issues/569

Signed-off-by: Nadav Goldin <ngoldin@redhat.com>

### CODE REVIEW

**Comment by nvgoldin** [comment]
Theoretically we would want it to be shown as a "test" so we'll get boot up time for each service and could compare trends, though didn't think of a good way to do it efficiently yet.
For now we can use this to investigate per patch.

**Comment by nvgoldin** [comment]
el73  - http://jenkins.ovirt.org/job/lago_master_github_check-merged-el7-x86_64/114/artifact/exported-artifacts/test_results/functional-sdk/test_results_sdk/test_sdk_sanity/collect/vm-el7-3-base/_root_virt-sysprep-firstboot.log

debian - http://jenkins.ovirt.org/job/lago_master_github_check-merged-el7-x86_64/114/artifact/exported-artifacts/test_results/functional-sdk/test_results_sdk/test_sdk_sanity/collect/vm-debian8-base/_root_virt-sysprep-firstboot.log

Ubuntu didn't finish running when the command was executed :/ might need to add a sleep there

http://jenkins.ovirt.org/job/lago_master_github_check-merged-el7-x86_64/114/artifact/exported-artifacts/test_results/functional-sdk/test_results_sdk/test_sdk_sanity/collect/vm-ubuntu16-04-base/_root_virt-sysprep-firstboot.log

**Comment by mykaul** [comment]
I wonder if we can disable NetworkManager if we use ifcfg files on EL7.3.
(Though I'd do the opposite and support NetworkManager and not write the
ifcfg files, if possible).

**Comment by nvgoldin** [comment]
1. do you think it will improve the boot time? I guess whatever we'll use most of those ~ 7 seconds go to DHCP.
2. IIRC - I tested el7.3 without ifcfg scripts and it worked fine - but question is whether https://github.com/lago-project/lago/pull/521#issuecomment-297640155 is still relevant.

**Comment by mykaul** [comment]
It doesn't seem to save boot time, so I guess we can leave it as is.

**Comment by nvgoldin** [comment]
Updated results in:
http://jenkins.ovirt.org/job/lago_master_github_check-merged-el7-x86_64/117/artifact/exported-artifacts/test_results/functional-sdk/test_results_sdk/test_sdk_sanity/systemd-analyze-vm-fc25-base.txt

http://jenkins.ovirt.org/job/lago_master_github_check-merged-el7-x86_64/117/artifact/exported-artifacts/test_results/functional-sdk/test_results_sdk/test_sdk_sanity/systemd-analyze-vm-el7-3-base.txt

Suprisingly, el7.3 boots much slower than fc25, it seems like the blame is:
```
          5.380s NetworkManager-wait-online.service
```
Which is simply not there on fc25(but there is NetworkManager). Reading http://forums.fedoraforum.org/showthread.php?t=302783 looks like it needs to be there - though I wonder how they got rid of it in fc25..

**Comment by nvgoldin** [comment]
ci merge please

**Comment by mykaul** [comment]
I've just noticed there are DNS issues on some interfaces while running. Specifically the IPv6 with the bonding network. May or may not be related. Considering the bonding network does not really need an IP at all, I wonder if we should add an option not to set them at all - not an IP nor DNS.

**Comment by nvgoldin** [comment]
> I've just noticed there are DNS issues on some interfaces while running.

Which issues did you see? 

> I wonder if we should add an option not to set them at all - not an IP nor DNS.

We could add an option per NIC in the init file to skip it. Though when we move to NM, we won't control it anyway..

**Comment by mykaul** [comment]
Jun 20 09:41:32 ovirtdemo dnsmasq[24242]: bad DHCP host name at line 20 of /var/lib/libvirt/dnsmasq/d18e-9465d1e2f8.hostsfile
Jun 20 09:41:32 ovirtdemo dnsmasq[24242]: bad DHCP host name at line 19 of /var/lib/libvirt/dnsmasq/d18e-9465d1e2f8.hostsfile
Jun 20 09:41:32 ovirtdemo dnsmasq[24242]: bad DHCP host name at line 18 of /var/lib/libvirt/dnsmasq/d18e-9465d1e2f8.hostsfile
Jun 20 09:41:32 ovirtdemo dnsmasq[24242]: bad DHCP host name at line 17 of /var/lib/libvirt/dnsmasq/d18e-9465d1e2f8.hostsfile
Jun 20 09:41:32 ovirtdemo dnsmasq[24242]: bad DHCP host name at line 16 of /var/lib/libvirt/dnsmasq/d18e-9465d1e2f8.hostsfile
Jun 20 09:41:32 ovirtdemo dnsmasq[24242]: bad DHCP host name at line 13 of /var/lib/libvirt/dnsmasq/d18e-9465d1e2f8.hostsfile

But I'll dig into it and try to reproduce.

**Pull request merged**
