### PR TITLE
qemu: raise informative exception on missing permissions

### PR DESCRIPTION
**Pull request by gbenhaim**
Print an informative message when qemu doesn't have
permissions to the storage files of the VMs.

Signed-off-by: gbenhaim <galbh2@gmail.com>

### CODE REVIEW

**Comment by gbenhaim** [comment]
ci test please

**Comment by gbenhaim** [comment]
ci test please

**Comment by eedri** [comment]
just a note this doesn't have to be RHEL CSB, it can be any OS with a remote user.

**Comment by gbenhaim** [comment]
ci merge please

**Pull request merged**
