### PR TITLE
Remove the memory balloon device. We don't use it.

### PR DESCRIPTION
**Pull request by mykaul**
The less devices the better. 
(I'm wondering what else we can remove, move to virtio, etc.)

### CODE REVIEW

**Comment by david-caro** [comment]
I just merged a patch that added quite a few new tests, can you rebase on top of it so the checks run all the new tests too?

**Comment by mykaul** [comment]
@david-caro  - don't think it's anything I've contributed to  - but 'make check' fails:
===================================================================================================== ERRORS ======================================================================================================
________________________________________________________________________________ ERROR collecting tests/unit/lago/test_workdir.py _________________________________________________________________________________
tests/unit/lago/test_workdir.py:26: in <module>
    import mock
E   ImportError: No module named mock
======================================================================================= 30 passed, 1 error in 1.67 seconds ========================================================================================
Makefile:54: recipe for target 'check-local' failed

**Comment by mykaul** [comment]
[ykaul@ykaul lago]$ rpm -qa |grep mock
mock-1.2.15-1.fc23.noarch

**Comment by david-caro** [comment]
it's not that mock, it's python-mock, did you pip instal -r test-requires.txt? (I recommend using a venv if using pip)

**Comment by mykaul** [comment]
============================================================================================ 74 passed in 1.47 seconds ============================================================================================
-------------------------------------------------------------
-------------------------------------------------------------
[ykaul@ykaul lago]$ 


All good!

**Comment by david-caro** [comment]
nice :smiley:

**Comment by david-caro** [comment]
you can try running the functional too, though I really recommend using mock_runner.sh for that (mock_runner.sh -p fc23 for the 'lightweight' ones, no download if images required, mock_runner.sh -m fc23 for the 'heavy' ones, that download a fc23 image)

**Comment by david-caro** [comment]
btw. the above el7 bug is fixed on master already (we were having false positives, that skipped that bug)

**Comment by mykaul** [comment]
[ykaul@ykaul lago]$ mock_runner.sh -p fc23
bash: mock_runner.sh: command not found...

**Comment by david-caro** [comment]
mmm... you did not rebase, you merged :/, try:

  git rebase -i origin/master

And set the merge commit as 'squash'

About mock_runner.sh see [this](http://lago.readthedocs.org/en/latest/Env_Setup.html#setting-up-mock-runner-sh-with-mock-fedora)

**Comment by mykaul** [comment]
I tried so hard to rebase :(

[ykaul@ykaul lago]$ git rebase -f upstream/master 
Current branch remove_balloon is up to date, rebase forced.
First, rewinding head to replay your work on top of it...
Applying: Remove the memory balloon device. We don't use it.
[ykaul@ykaul lago]$ git log
commit c9d8555415bf236bbac367e2c58aeed97ab1490a
Author: Yaniv Kaul <ykaul@redhat.com>
Date:   Wed Mar 9 20:48:25 2016 +0200

    Remove the memory balloon device. We don't use it.

commit 1103cdda0e14f9ca5ad01ebd0f4f4b7ecbb2d3bb
Merge: 44b93c7 de3f651
Author: Lago CI bot <dcaroest+cibot@redhat.com>
Date:   Wed Mar 9 19:59:47 2016 +0100

    Merge pull request #157 from lago-project/add_workdir
    
    Added workdir element

commit de3f651b339fe10b3ea55810bd4d659ed02b5fc7
Author: David Caro <dcaroest@redhat.com>
Date:   Wed Mar 9 18:27:54 2016 +0100

    functional:Fixed tests on el7
    
    Change-Id: I51fd53532d62cf76b78bd5874f629695379b32ba
    Signed-off-by: David Caro <dcaroest@redhat.com>

commit e38d43adb2e490133093941025e5a772afb181bf
Author: David Caro <dcaroest@redhat.com>
Date:   Wed Mar 9 18:01:21 2016 +0100

    Don't require tty for sudoing from lago
    
    Change-Id: Ic7844682046c4e5bd94ce75e548ced1cd3333f6d
    Signed-off-by: David Caro <dcaroest@redhat.com>

commit 354f9a93bbc821554672a17ea756b3cd2feb906b
Author: David Caro <dcaroest@redhat.com>
Date:   Wed Mar 9 17:39:08 2016 +0100

    Fixed el7 python lib issues
    
    Change-Id: Iaec2c5d870de8c22df7f9fb96a8e4c40cf1902d4
    Signed-off-by: David Caro <dcaroest@redhat.com>

commit 44b93c707bb2434980c29dc246348b703bb2b42f
Merge: 4843a75 89fa3de
Author: Lago CI bot <dcaroest+cibot@redhat.com>
Date:   Wed Mar 9 17:29:45 2016 +0100

    Merge pull request #169 from mykaul/ignore_empty_rpms_on_merge
    
[ykaul@ykaul lago]$ git push
warning: push.default is unset; its implicit value has changed in
Git 2.0 from 'matching' to 'simple'. To squelch this message
and maintain the traditional behavior, use:

  git config --global push.default matching

To squelch this message and adopt the new behavior now, use:

  git config --global push.default simple

When push.default is set to 'matching', git will push local branches
to the remote branches that already exist with the same name.

Since Git 2.0, Git defaults to the more conservative 'simple'
behavior, which only pushes the current branch to the corresponding
remote branch that 'git pull' uses to update the current branch.

See 'git help config' and search for 'push.default' for further information.
(the 'simple' mode was introduced in Git 1.7.11. Use the similar mode
'current' instead of 'simple' if you sometimes use older versions of Git)

To git@github.com:mykaul/lago.git
 ! [rejected]        remove_balloon -> remove_balloon (non-fast-forward)
error: failed to push some refs to 'git@github.com:mykaul/lago.git'
hint: Updates were rejected because the tip of your current branch is behind
hint: its remote counterpart. Integrate the remote changes (e.g.
hint: 'git pull ...') before pushing again.
hint: See the 'Note about fast-forwards' in 'git push --help' for details.
[ykaul@ykaul lago]$ git status
On branch remove_balloon
Your branch and 'origin/remove_balloon' have diverged,
and have 24 and 1 different commit each, respectively.
  (use "git pull" to merge the remote branch into yours)
nothing to commit, working directory clean


I merged based on http://stackoverflow.com/questions/19016698/git-branch-diverged-after-rebase

**Comment by david-caro** [comment]
don't just push!! it's quite dangerous, as it will 'guess' what to push (which branch, with tags...), specify the remote and the branch, also, if you rebase, you have to --force too:

    git push --force origin remove_balloon

That is if your origin is your fork

**Comment by david-caro** [comment]
So the usual way of rebasing is (upstream being the lago-project/lago remote and origin mykaul/lago):

    git fetch upstream
    git rebase upstream/master
    # solve any conflicts
    git push --force origin my_feature_branch

**Comment by david-caro** [comment]
Now looks ok :+1:

**Comment by david-caro** [comment]
ci merge please

**Comment by david-caro** [comment]
ci :shipit:

**Comment by david-caro** [comment]
jenkins got out of space and messed up a lot of things... retrying
ci :shipit:

**Pull request merged**
