### PR TITLE
Bump yapf version 0.7.1 -> 0.14.0

### PR DESCRIPTION
**Pull request by nvgoldin**
New flake8 versions are no longer compatible with
the old yapf version used.

1. Fixed 2 flake8 errors.
2. Fixed few docstring/RST errors.
3. Adjusted scripts/check_style.sh to the new yapf exit
codes.
4. Rest of the changes were generated by running
the new yapf(0.14.0) on rest of the code.

closes: https://github.com/lago-project/lago/issues/321

### CODE REVIEW

**Comment by david-caro** [comment]
We pinned the version of yapf because it wasn't compañía ible with the lates pep8, glad to see them work ok together again :)

**Comment by david-caro** [comment]
Damn autocorrection... Hehehe

**Comment by nvgoldin** [comment]
@david-caro great ;) hope indeed they will work nicely together, so far tested it locally with some none-styled code and it looked OK.

**Comment by nvgoldin** [comment]
copy&pasting some more details from lago-devel mailing list for future references:
>To make a long story short, this change[1] in flake8 allowed
pycodestyle 2.2.0(formerly known as pep8) to be used, which in its
turn was not behaving nicely with our current yapf installation.
Instead of seeking where/why/how we can keep the old versions, I
updated to a new yapf version(0.14.0, we were using 0.7.1), which seem
to also make the code look a bit better.
Once [2] hopefully passes CI and merged, rebase on master and update
the yapf version:
pip install --upgrade yapf
(pip is how the automation script installs it too, so no RPM needed),
hopefully this will solve it.
[1] http://flake8.pycqa.org/en/latest/release-notes/3.2.0.html
[2] https://github.com/lago-project/lago/pull/367

**Comment by gbenhaim** [comment]
+1

**Comment by nvgoldin** [comment]
ci merge please

**Comment by david-caro** [comment]
I strongly advise against mixing pip and rpm deps, in this case is only for the tests, so it's kind of less relevant, but it's good to not use this as a recedent for installation dependencies.

**Comment by nvgoldin** [comment]
:+1:

**Pull request merged**
