### PR TITLE
Document type field for nets

### PR DESCRIPTION
**Pull request by d3dave**

### CODE REVIEW

**Comment by ovirt-infra** [comment]
The commiter is not a member of organization nor whitelist. Please contact maintainer for patch verification.

**Comment by ovirt-infra** [comment]
The commiter is not a member of organization nor whitelist. Please contact maintainer for patch verification.

**Comment by ovirt-infra** [comment]
The commiter is not a member of organization nor whitelist. Please contact maintainer for patch verification.

**Comment by ovirt-infra** [comment]
The commiter is not a member of organization nor whitelist. Please contact maintainer for patch verification.

**Comment by ovirt-infra** [comment]
The commiter is not a member of organization nor whitelist. Please contact maintainer for patch verification.

**Comment by ovirt-infra** [comment]
The commiter is not a member of organization nor whitelist. Please contact maintainer for patch verification.

**Comment by ovirt-infra** [comment]
The commiter is not a member of organization nor whitelist. Please contact maintainer for patch verification.

**Comment by ovirt-infra** [comment]
The commiter is not a member of organization nor whitelist. Please contact maintainer for patch verification.

**Comment by ovirt-infra** [comment]
The commiter is not a member of organization nor whitelist. Please contact maintainer for patch verification.

**Comment by ovirt-infra** [comment]
The commiter is not a member of organization nor whitelist. Please contact maintainer for patch verification.

**Comment by ovirt-infra** [comment]
The commiter is not a member of organization nor whitelist. Please contact maintainer for patch verification.

**Comment by ovirt-infra** [comment]
The commiter is not a member of organization nor whitelist. Please contact maintainer for patch verification.

**Comment by ovirt-infra** [comment]
The commiter is not a member of organization nor whitelist. Please contact maintainer for patch verification.

**Comment by nvgoldin** [comment]
Thanks!

**Comment by nvgoldin** [comment]
ci test please

**Comment by nvgoldin** [comment]
Once CI finishes the rendered docs should be at:
http://jenkins.ovirt.org/job/lago_master_github_check-patch-fc24-x86_64/464/artifact/exported-artifacts/docs/html/index.html

The output should be the same as running locally ``tox -e docs`` and then browsing ``firefox docs/_build/html/index.html``

**Comment by d3dave** [comment]
@nvgoldin 
> Once CI finishes the rendered docs should be at:
http://jenkins.ovirt.org/job/lago_master_github_check-patch-fc24-x86_64/464/artifact/exported-artifacts/docs/html/index.html

The build number is 465, so at http://jenkins.ovirt.org/job/lago_master_github_check-patch-fc24-x86_64/464/artifact/exported-artifacts/docs/html/index.html

**Comment by nvgoldin** [comment]
ci merge please

**Pull request merged**
