### PR TITLE
ovirtlago:Added a wait for the engine to go up

### PR DESCRIPTION
**Pull request by david-caro**
It was working before because we did not handle exceptions properly

### CODE REVIEW

**Comment by david-caro** [comment]
ci :shipit:

**Comment by mykaul** [comment]
I added to the engine setup test a check that verifies the engine is up. Once it is - why check again?

**Comment by david-caro** [comment]
You can, and we do take the engine down a few times after it's set up, so that's not enough.

**Comment by mykaul** [comment]
@david-caro I believe it's https://gerrit.ovirt.org/#/c/53518/ - not sure why it's not merged yet.

**Comment by david-caro** [comment]
@mykaul let's get the tests working before doing any more improvements, please review https://gerrit.ovirt.org/#/c/53534/, it's been around for quite a long time and that fixes the current 3.6 tests on jenkins (been failing since forever).

Once we get a working setup, we can focus on improving it

**Comment by david-caro** [comment]
ci test please

**Comment by david-caro** [comment]
ci :shipit:

**Comment by david-caro** [comment]
ci :shipit:

**Pull request merged**
