### PR TITLE
Set MTU per interface.

### PR DESCRIPTION
**Pull request by mykaul**
Apparently, it's not enough to set it for the network.
It needs to be set up per the interface as well.
For example:
    nics:
      - net: lago-{{ env.suite_name}}-net-management
      - net: lago-{{ env.suite_name}}-net-storage
        mtu: 9000

Would set MTU 9000 to net-storage.

(It should match the network too!)

### CODE REVIEW

**Comment by ovirt-infra** [comment]
Build finished.

**Comment by ovirt-infra** [comment]
Build finished.

**Comment by ovirt-infra** [comment]
Build finished.

**Comment by ovirt-infra** [comment]
Build finished.

**Comment by ovirt-infra** [comment]
Build finished.

**Comment by ovirt-infra** [comment]
Build finished.

**Comment by ovirt-infra** [comment]
Build finished.

**Comment by ovirt-infra** [comment]
Build finished.

**Comment by ovirt-infra** [comment]
Build finished.

**Comment by ovirt-infra** [comment]
Build finished.

**Comment by ovirt-infra** [comment]
Build finished.

**Comment by ovirt-infra** [comment]
Build finished.

**Comment by gbenhaim** [comment]
Why not take the MTU size from the network definition?
It will ensure that a nic and its corresponding network will always have the same MTU.
It will also require fewer configurations in the init file.

**Comment by mykaul** [comment]
Hmm, unsure how do I get to the network definition from the device scope. I can get the network name, not sure how I dive into its properties...

**Comment by gbenhaim** [comment]
In `prefix.Prefix._config_net_topology` copy the MTU from the net config to the domain config.

**Comment by ovirt-infra** [comment]
Build finished.

**Comment by ovirt-infra** [comment]
Build finished.

**Comment by ovirt-infra** [comment]
Build finished.

**Comment by ovirt-infra** [comment]
Build finished.

**Comment by ovirt-infra** [comment]
Build finished.

**Comment by ovirt-infra** [comment]
Build finished.

**Comment by ovirt-infra** [comment]
Build finished.

**Comment by ovirt-infra** [comment]
Build finished.

**Comment by ovirt-infra** [comment]
Build finished.

**Comment by ovirt-infra** [comment]
Build finished.

**Comment by ovirt-infra** [comment]
Build finished.

**Comment by ovirt-infra** [comment]
Build finished.

**Comment by mykaul** [comment]
ci please test

**Comment by mykaul** [comment]
@gbenhaim - I can't satisfy both yapf and flake8 for some reason... Any ideas?

**Comment by gbenhaim** [comment]
It looks like that something was wrong with the parentheses.
The following format pass the checks:

```python

    def _get_net(self, conf, dom_name, nic):
        try:
            net = conf['nets'][nic['net']]
        except KeyError:
            raise LagoInitException(
                dedent(
                    """
                    Unrecognized network in {0}: {1},
                    available: {2}
                    """.format(
                        dom_name,
                        nic['net'],
                        ','.join(conf.get('nets', {}).keys()),
                    )
                )
            )

        return net
```

The comma at the last argument given to "format", indicates to yapf that each argument should be kept in a new line.

**Comment by ovirt-infra** [comment]
Build finished.

**Comment by ovirt-infra** [comment]
Build finished.

**Comment by ovirt-infra** [comment]
Build finished.

**Comment by ovirt-infra** [comment]
Build finished.

**Comment by ovirt-infra** [comment]
Build finished.

**Comment by ovirt-infra** [comment]
Build finished.

**Comment by ovirt-infra** [comment]
Build finished.

**Comment by ovirt-infra** [comment]
Build finished.

**Comment by ovirt-infra** [comment]
Build finished.

**Comment by ovirt-infra** [comment]
Build finished.

**Comment by ovirt-infra** [comment]
Build finished.

**Comment by ovirt-infra** [comment]
Build finished.

**Comment by ovirt-infra** [comment]
Build finished.

**Comment by ovirt-infra** [comment]
Build finished.

**Comment by ovirt-infra** [comment]
Build finished.

**Comment by ovirt-infra** [comment]
Build finished.

**Comment by ovirt-infra** [comment]
Build finished.

**Comment by ovirt-infra** [comment]
Build finished.

**Comment by ovirt-infra** [comment]
Build finished.

**Comment by ovirt-infra** [comment]
Build finished.

**Comment by ovirt-infra** [comment]
Build finished.

**Comment by ovirt-infra** [comment]
Build finished.

**Comment by ovirt-infra** [comment]
Build finished.

**Comment by ovirt-infra** [comment]
Build finished.

**Comment by gbenhaim** [comment]
ci merge please

**Comment by gbenhaim** [comment]
ci merge please

**Comment by gbenhaim** [comment]
ci test please

**Comment by gbenhaim** [comment]
ci test please

**Comment by gbenhaim** [comment]
ci merge please

**Pull request merged**
