### PR TITLE
Use python2 explicitly.

### PR DESCRIPTION
**Pull request by lenoch**
Currently, the code still uses constructs incompatible with Python 3, and so we should run it with the python2 binary.

### CODE REVIEW

**Comment by nvgoldin** [comment]
ci test please

**Comment by ifireball** [comment]
We probably need to be consistent about using `#!/usr/bin/python2` or `#!/usr/bin/env python2`. Maybe Fedora has some guidelines about what is better to use?

**Comment by nvgoldin** [comment]
I think we need ``` /usr/bin/env python2 ``` in order to support virtualenv, however, iirc, for official RPMs the requirement is to put ```/usr/bin/python2``` explicitly.

**Comment by lenoch** [comment]
There was a proposal back during Fedora 16 cycle but I am not sure whether it took off. https://fedoraproject.org/wiki/Features/SystemPythonExecutablesUseSystemPython

If we wanted to support systems which place their binaries outside /usr/bin we would be better off using /usr/bin/env python2.

**Comment by lenoch** [comment]
It failed because of `12:32:33 Error: No Package found for python2-crypto = 2.6.1-10.el7` on EL7.

**Comment by ifireball** [comment]
Yeah EPEL does not keep history and newer python2-crypto breaks Paramiko. I think @nvgoldin is working on a work-around.

**Comment by nvgoldin** [comment]
@lenoch - yep this is https://github.com/lago-project/lago/issues/440, I'm working on a fix now.
I vote for /usr/bin/env python2 (if it passes CI, which means we're safe and then we can use it in venv too)

**Comment by lenoch** [comment]
@nvgoldin Yes, voting for that too. I'll push that to the same branch as another commit, okay?

**Comment by nvgoldin** [comment]
@lenoch - to this branch you mean? if so just amend this one.
though will need a rebase after I merge the fix for python2-crypto.

**Comment by lenoch** [comment]
@nvgoldin Yep, I meant this branch and thought of adding a new commit. But I can do the unification of hashbangs in the same commit as well. I can wait for you to push #440 and rebase afterwards.

**Comment by nvgoldin** [comment]
ci test please

**Comment by nvgoldin** [comment]
@lenoch,
1. I added you as a member to the project, so CI should be triggered automatically when you push, or you can comment with 'ci test please'
2. Unfortunately my fix isn't merged yet - some other unexpected problems arose. I'll ping you here when its merged.

**Comment by nvgoldin** [comment]
@lenoch  - fixes were merged, feel free to rebase.

**Comment by lenoch** [comment]
I have been using this latest rebased version without a hassle, I think you can merge it @nvgoldin :-)

**Comment by nvgoldin** [comment]
Thanks!  works for me too. Running CI again as some Jenkins jobs changed.

**Comment by nvgoldin** [comment]
ci test please

**Comment by nvgoldin** [comment]
unrelated ci failure, mirrors issue

**Comment by nvgoldin** [comment]
ci test please

**Comment by lenoch** [comment]
ci test please

**Comment by nvgoldin** [comment]
https://ovirt-jira.atlassian.net/browse/OVIRT-1118 -> the reason.

**Comment by nvgoldin** [comment]
ci test please

**Comment by nvgoldin** [comment]
ci test please

**Comment by nvgoldin** [comment]
ci test please

**Comment by nvgoldin** [comment]
ci test please

**Comment by nvgoldin** [comment]
ci test please

**Comment by nvgoldin** [comment]
ci merge please

**Pull request merged**
