### PR TITLE
Moved python-nose dep to main package

### PR DESCRIPTION
**Pull request by david-caro**
Change-Id: If9bbd7a4f1d39d51177928821ab9985d7b9ea040
Signed-off-by: David Caro <dcaroest@redhat.com>

### CODE REVIEW

**Comment by david-caro** [comment]
@ifireball Let me know if this fixes the issue

**Comment by david-caro** [comment]
ci test please

**Comment by david-caro** [comment]
Fixes #99

**Comment by ifireball** [comment]
Hmm... why does main Lago need nose? Maybe we should remove the stuff that need it?

**Comment by david-caro** [comment]
That's for the integration with nose, mainly the logging stuff here as the test-specific stuff is on the ovirt package

**Comment by david-caro** [comment]
There's 0 stuff using it on lago main package, moved it

**Comment by david-caro** [comment]
Moved to #118

**Pull request closed without merging**
