### PR TITLE
all "supported" OS use systemctl instead of service

### PR DESCRIPTION
**Pull request by mkopta**

### CODE REVIEW

**Comment by david-caro** [comment]
ci test please

**Comment by david-caro** [comment]
Can you rebase please?

**Comment by mkopta** [comment]
Sure, rebased.

**Comment by david-caro** [comment]
ci test please

**Comment by mykaul** [comment]
@mkopta  - 3.6 oVirt engine is still running EL 6.x, how does that work?

**Comment by david-caro** [comment]
ci test please

**Comment by david-caro** [comment]
ci test please

**Comment by david-caro** [comment]
sorry for the noise, had to fix a couple of issues with the fc24 checks and such

**Comment by david-caro** [comment]
ci :shipit:

**Comment by david-caro** [comment]
ci :shipit:

**Comment by david-caro** [comment]
ci :shipit:

**Comment by david-caro** [comment]
Same as the other, can you rebase please? :pray:

**Comment by mkopta** [comment]
Sure, no problem. Rebased.

**Comment by david-caro** [comment]
ci test please

**Comment by david-caro** [comment]
ci :shipit:

**Comment by david-caro** [comment]
ci :shipit:

**Comment by david-caro** [comment]
dammit... it needs rebase again, it seems that the other change that was merged just before this one added a conflict and now github complains that the merge commit that the deploy pipeline tested and tried to merge did not run the tests... hmm, maybe I should deactivate that requirement :/

**Comment by mkopta** [comment]
It is okay, I really don't mind to rebase.

**Comment by david-caro** [comment]
I really miss the possibility to do that 'maintenance dummy rebasing' by the receiver of the pull request intead :], thanks a lot for the patience though!

**Comment by david-caro** [comment]
ci test please

**Comment by david-caro** [comment]
ci :shipit:

**Pull request merged**
